sonarQube:
  version: "9.3.0"
  replicaCount: 1
  image:
    repository: sonarqube
    tag: "9.3.0-community"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

persistence:
  enabled: true
  storageClass: "standard"
  size: 10Gi

serviceAccount:
  create: true
  automount: true  # This prevents another nil error
  annotations: {}  # Ensure this is defined, even if empty

autoscaling:
  enabled: false  # Change to true if you want HPA enabled
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
