apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sonarqube
  labels:
    app: sonarqube
spec:
  replicas: {{ .Values.sonarQube.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: "{{ .Values.sonarQube.image.repository | default "sonarqube" }}:{{ .Values.sonarQube.image.tag | default "latest" }}"
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "{{ .Values.sonarQube.resources.requests.memory | default "512Mi" }}"
              cpu: "{{ .Values.sonarQube.resources.requests.cpu | default "500m" }}"
            limits:
              memory: "{{ .Values.sonarQube.resources.limits.memory | default "1Gi" }}"
              cpu: "{{ .Values.sonarQube.resources.limits.cpu | default "1" }}"

          volumeMounts:
            - name: sonarqube-pvc
              mountPath: /opt/sonarqube/data
      volumes:
        - name: sonarqube-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-sonarqube-pvc
