apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sonarqube
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: {{ .Values.sonarQube.service.port }}
      targetPort: 9000
  port: {{ .Values.sonarQube.service.port }}
  type: {{ .Values.sonarQube.service.type }}


